name: Update PDF Count

on:
  schedule:
    # - cron: "0 * * * *"  # Runs every hour
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PDF Count Script
        run: python count_pdfs.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pdf_status.json
          git commit -m "Update PDF count"
          git push
